# Generated by Django 6.0.7 on 2026-09-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='extraction_status',
            field=models.CharField(choices=[('none', 'No file uploaded'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
    ]
